"""Machine-readable exports so a ThreatForge draft flows into existing tooling.

Three export targets:

* **native JSON** - the full system model + threat register, ThreatForge's own
  interchange format.
* **pytm-compatible** - a Python script using the ``pytm`` threats-as-code DSL,
  so the recovered model can be opened/extended in pytm.
* **OWASP Threat Dragon** - a ``.json`` model importable by Threat Dragon's
  editor, so a reviewer can continue in a GUI.

These are best-effort structural exports; a human reviews the result in the
target tool. We target the widely-used shapes of each format.
"""

from __future__ import annotations

import json

from ..model.schema import ElementType, SystemModel
from ..reason.threat import Threat


def to_native_json(model: SystemModel, threats: list[Threat]) -> str:
    return json.dumps(
        {
            "tool": "ThreatForge",
            "model": model.to_dict(),
            "threats": [t.to_dict() for t in threats],
        },
        indent=2,
    )


def to_pytm(model: SystemModel, threats: list[Threat]) -> str:
    """Emit a pytm script describing the recovered model (threats as comments)."""
    lines = [
        "# pytm model generated by ThreatForge (threats-as-code).",
        "# Review and extend in pytm: https://github.com/OWASP/pytm",
        "from pytm import TM, Server, Datastore, Actor, Dataflow, Boundary",
        "",
        f'tm = TM("{_s(model.name)}")',
        "",
    ]
    var: dict[str, str] = {}
    # Boundaries.
    for i, b in enumerate(model.boundaries):
        v = f"b{i}"
        lines.append(f'{v} = Boundary("{_s(b.name)}")')
    lines.append("")
    # Elements.
    for el in model.elements:
        if el.type == ElementType.DATA_FLOW:
            continue
        v = _var(el.id)
        var[el.id] = v
        if el.type == ElementType.PROCESS:
            lines.append(f'{v} = Server("{_s(el.name)}")')
        elif el.type == ElementType.DATA_STORE:
            lines.append(f'{v} = Datastore("{_s(el.name)}")')
        else:
            lines.append(f'{v} = Actor("{_s(el.name)}")')
    lines.append("")
    # Flows.
    for i, fl in enumerate(model.flows):
        s, d = var.get(fl.source), var.get(fl.dest)
        if not s or not d:
            continue
        v = f"df{i}"
        lines.append(f'{v} = Dataflow({s}, {d}, "{_s(fl.name or "flow")}")')
        lines.append(f'{v}.protocol = "{_s(fl.protocol)}"')
        lines.append(f"{v}.isEncrypted = {bool(fl.encrypted)}")
        if fl.data:
            lines.append(f'{v}.data = "{_s(", ".join(fl.data))}"')
    lines.append("")
    lines.append("# --- ThreatForge candidate threats (for review) ---")
    for t in threats:
        lines.append(
            f"# [{t.id}] {t.stride_name} / {t.component}: {t.title} "
            f"(risk {t.risk} {t.risk_level}; {', '.join(t.controls)})"
        )
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    tm.process()")
    return "\n".join(lines) + "\n"


def to_threat_dragon(model: SystemModel, threats: list[Threat]) -> str:
    """Emit an OWASP Threat Dragon importable model JSON."""
    threats_by_component: dict[str, list[Threat]] = {}
    for t in threats:
        threats_by_component.setdefault(t.component_id, []).append(t)

    cells = []
    positions = _grid_positions(model)
    for el in model.elements:
        if el.type == ElementType.DATA_FLOW:
            continue
        x, y = positions[el.id]
        td_type = {
            ElementType.PROCESS: "tm.Process",
            ElementType.DATA_STORE: "tm.Store",
            ElementType.EXTERNAL_ENTITY: "tm.Actor",
        }[el.type]
        cell_threats = [
            {
                "id": t.id,
                "title": t.title,
                "type": t.stride_name,
                "status": "Open",
                "severity": t.risk_level,
                "description": t.rationale,
                "mitigation": t.mitigation,
            }
            for t in threats_by_component.get(el.id, [])
        ]
        cells.append(
            {
                "type": td_type,
                "id": el.id,
                "position": {"x": x, "y": y},
                "size": {"width": 160, "height": 80},
                "attrs": {"text": {"text": el.name}},
                "data": {
                    "type": td_type,
                    "name": el.name,
                    "threats": cell_threats,
                    "hasOpenThreats": bool(cell_threats),
                },
            }
        )
    for fl in model.flows:
        cells.append(
            {
                "type": "tm.Flow",
                "id": fl.id,
                "source": {"cell": fl.source},
                "target": {"cell": fl.dest},
                "labels": [fl.name or "flow"],
                "data": {
                    "type": "tm.Flow",
                    "name": fl.name or "flow",
                    "isEncrypted": bool(fl.encrypted),
                    "protocol": fl.protocol,
                    "threats": [],
                },
            }
        )

    doc = {
        "version": "2.0",
        "summary": {"title": model.name, "owner": "Krishita Sanjay Choksi",
                    "description": "Draft threat model generated by ThreatForge."},
        "detail": {
            "contributors": [{"name": "Krishita Sanjay Choksi"}],
            "diagrams": [
                {
                    "id": 0,
                    "title": "Main DFD",
                    "diagramType": "STRIDE",
                    "cells": cells,
                }
            ],
        },
    }
    return json.dumps(doc, indent=2)


def _grid_positions(model: SystemModel) -> dict[str, tuple[int, int]]:
    from ..model.schema import TrustZone

    order = list(TrustZone)
    cols: dict[TrustZone, int] = {z: 0 for z in order}
    pos: dict[str, tuple[int, int]] = {}
    for el in model.elements:
        if el.type == ElementType.DATA_FLOW:
            continue
        col = order.index(el.zone)
        row = cols[el.zone]
        cols[el.zone] += 1
        pos[el.id] = (120 + col * 220, 100 + row * 140)
    return pos


def _s(s: str) -> str:
    return s.replace('"', "'").replace("\n", " ")


def _var(eid: str) -> str:
    v = "".join(ch if ch.isalnum() else "_" for ch in eid)
    return f"e_{v}"
