"""Machine-readable exports so a ThreatForge draft flows into existing tooling.

Three export targets:

* **native JSON** - the full system model + threat register, ThreatForge's own
  interchange format.
* **pytm-compatible** - a Python script using the ``pytm`` threats-as-code DSL,
  so the recovered model can be opened/extended in pytm.
* **OWASP Threat Dragon** - a ``.json`` model importable by Threat Dragon's
  editor, so a reviewer can continue in a GUI.

These are best-effort structural exports; a human reviews the result in the
target tool. We target the widely-used shapes of each format.
"""

from __future__ import annotations

import json

from ..model.schema import ElementType, SystemModel
from ..reason.threat import Threat


def to_native_json(model: SystemModel, threats: list[Threat]) -> str:
    return json.dumps(
        {
            "tool": "ThreatForge",
            "model": model.to_dict(),
            "threats": [t.to_dict() for t in threats],
        },
        indent=2,
    )


def to_pytm(model: SystemModel, threats: list[Threat]) -> str:
    """Emit a pytm script describing the recovered model (threats as comments)."""
    lines = [
        "# pytm model generated by ThreatForge (threats-as-code).",
        "# Review and extend in pytm: https://github.com/OWASP/pytm",
        "from pytm import TM, Server, Datastore, Actor, Dataflow, Boundary",
        "",
        f'tm = TM("{_s(model.name)}")',
        "",
    ]
    var: dict[str, str] = {}
    # Boundaries.
    for i, b in enumerate(model.boundaries):
        v = f"b{i}"
        lines.append(f'{v} = Boundary("{_s(b.name)}")')
    lines.append("")
    # Elements.
    for el in model.elements:
        if el.type == ElementType.DATA_FLOW:
            continue
        v = _var(el.id)
        var[el.id] = v
        if el.type == ElementType.PROCESS:
            lines.append(f'{v} = Server("{_s(el.name)}")')
        elif el.type == ElementType.DATA_STORE:
            lines.append(f'{v} = Datastore("{_s(el.name)}")')
        else:
            lines.append(f'{v} = Actor("{_s(el.name)}")')
    lines.append("")
    # Flows.
    for i, fl in enumerate(model.flows):
        s, d = var.get(fl.source), var.get(fl.dest)
        if not s or not d:
            continue
        v = f"df{i}"
        lines.append(f'{v} = Dataflow({s}, {d}, "{_s(fl.name or "flow")}")')
        lines.append(f'{v}.protocol = "{_s(fl.protocol)}"')
        lines.append(f"{v}.isEncrypted = {bool(fl.encrypted)}")
        if fl.data:
            lines.append(f'{v}.data = "{_s(", ".join(fl.data))}"')
    lines.append("")
    lines.append("# --- ThreatForge candidate threats (for review) ---")
    for t in threats:
        lines.append(
            f"# [{t.id}] {t.stride_name} / {t.component}: {t.title} "
            f"(risk {t.risk} {t.risk_level}; {', '.join(t.controls)})"
        )
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    tm.process()")
    return "\n".join(lines) + "\n"


def to_threat_dragon(model: SystemModel, threats: list[Threat]) -> str:
    """Emit an OWASP Threat Dragon importable model JSON."""
    threats_by_component: dict[str, list[Threat]] = {}
    for t in threats:
        threats_by_component.setdefault(t.component_id, []).append(t)

    cells = []
    positions = _grid_positions(model)
    for el in model.elements:
        if el.type == ElementType.DATA_FLOW:
            continue
        x, y = positions[el.id]
        td_type = {
            ElementType.PROCESS: "tm.Process",
            ElementType.DATA_STORE: "tm.Store",
            ElementType.EXTERNAL_ENTITY: "tm.Actor",
        }[el.type]
        cell_threats = [
            {
                "id": t.id,
                "title": t.title,
                "type": t.stride_name,
                "status": "Open",
                "severity": t.risk_level,
                "description": t.rationale,
                "mitigation": t.mitigation,
            }
            for t in threats_by_component.get(el.id, [])
        ]
        cells.append(
            {
                "type": td_type,
                "id": el.id,
                "position": {"x": x, "y": y},
                "size": {"width": 160, "height": 80},
                "attrs": {"text": {"text": el.name}},
                "data": {
                    "type": td_type,
                    "name": el.name,
                    "threats": cell_threats,
                    "hasOpenThreats": bool(cell_threats),
                },
            }
        )
    for fl in model.flows:
        cells.append(
            {
                "type": "tm.Flow",
                "id": fl.id,
                "source": {"cell": fl.source},
                "target": {"cell": fl.dest},
                "labels": [fl.name or "flow"],
                "data": {
                    "type": "tm.Flow",
                    "name": fl.name or "flow",
                    "isEncrypted": bool(fl.encrypted),
                    "protocol": fl.protocol,
                    "threats": [],
                },
            }
        )

    doc = {
        "version": "2.0",
        "summary": {"title": model.name, "owner": "Krishita Sanjay Choksi",
                    "description": "Draft threat model generated by ThreatForge."},
        "detail": {
            "contributors": [{"name": "Krishita Sanjay Choksi"}],
            "diagrams": [
                {
                    "id": 0,
                    "title": "Main DFD",
                    "diagramType": "STRIDE",
                    "cells": cells,
                }
            ],
        },
    }
    return json.dumps(doc, indent=2)


def _grid_positions(model: SystemModel) -> dict[str, tuple[int, int]]:
    from ..model.schema import TrustZone

    order = list(TrustZone)
    cols: dict[TrustZone, int] = {z: 0 for z in order}
    pos: dict[str, tuple[int, int]] = {}
    for el in model.elements:
        if el.type == ElementType.DATA_FLOW:
            continue
        col = order.index(el.zone)
        row = cols[el.zone]
        cols[el.zone] += 1
        pos[el.id] = (120 + col * 220, 100 + row * 140)
    return pos


_SARIF_LEVEL = {"Critical": "error", "High": "error", "Medium": "warning", "Low": "note"}


def to_sarif(model: SystemModel, threats: list[Threat], anchor_file: str = "THREATMODEL.md") -> str:
    """Emit SARIF 2.1.0 so threats surface in the GitHub Security / code-scanning tab.

    Each distinct KB pattern becomes a SARIF rule; each threat becomes a result,
    with severity mapped to a SARIF level and rich help text (mitigation + mapped
    controls + CWE + OWASP Top 10). Results anchor to ``anchor_file`` so they are
    clickable in the GitHub UI.
    """
    rules: dict[str, dict] = {}
    results = []
    for t in threats:
        rule_id = t.source_pattern or f"{t.stride}-{t.component_id}"
        if rule_id not in rules:
            help_lines = [
                f"**{t.stride_name}** against `{t.component}`.",
                "",
                f"Mitigation: {t.mitigation}",
            ]
            if t.controls:
                help_lines.append(f"Controls: {', '.join(t.controls)}")
            if t.cwe:
                help_lines.append(f"Weakness: {t.cwe}")
            if t.owasp_top10:
                help_lines.append(f"OWASP Top 10: {t.owasp_top10}")
            rules[rule_id] = {
                "id": rule_id,
                "name": _rule_name(t.title),
                "shortDescription": {"text": t.title},
                "fullDescription": {"text": t.rationale or t.title},
                "helpUri": _cwe_uri(t.cwe),
                "help": {"text": "\n".join(help_lines),
                         "markdown": "\n".join(help_lines)},
                "defaultConfiguration": {"level": _SARIF_LEVEL.get(t.risk_level, "warning")},
                "properties": {
                    "stride": t.stride_name,
                    "cwe": t.cwe,
                    "owaspTop10": t.owasp_top10,
                    "security-severity": str(_security_severity(t.risk)),
                    "tags": ["security", "threat-model", "stride"],
                },
            }
        results.append({
            "ruleId": rule_id,
            "level": _SARIF_LEVEL.get(t.risk_level, "warning"),
            "message": {"text": f"[{t.id}] {t.title} - {t.component} "
                                f"(risk {t.risk}/{t.risk_level}). {t.rationale}"},
            "locations": [{
                "physicalLocation": {
                    "artifactLocation": {"uri": anchor_file},
                    "region": {"startLine": 1},
                },
                "logicalLocations": [{"name": t.component, "kind": "component"}],
            }],
            "properties": {"threatId": t.id, "boundary": t.boundary,
                           "likelihood": t.likelihood, "impact": t.impact},
        })

    doc = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {
                "name": "ThreatForge",
                "informationUri": "https://github.com/Krishita17/threat-forge",
                "version": "0.1.0",
                "rules": list(rules.values()),
            }},
            "results": results,
        }],
    }
    return json.dumps(doc, indent=2)


def to_mermaid_dfd(model: SystemModel) -> str:
    """Markdown-embeddable Mermaid DFD that GitHub renders natively.

    Unlike the input diagram format, this is styled for reading: zones as
    subgraphs, boundary-crossing unencrypted flows highlighted. Wrap in a
    ```mermaid fence to render inline on GitHub.
    """
    from ..model.schema import ElementType, TrustZone

    zlabel = {
        TrustZone.PUBLIC: "Public / Internet", TrustZone.DMZ: "Edge / DMZ",
        TrustZone.APPLICATION: "Application", TrustZone.DATA: "Data",
        TrustZone.THIRD_PARTY: "Third-party", TrustZone.TRUSTED: "Trusted / Admin",
    }
    shape = {ElementType.PROCESS: ("([", "])"), ElementType.DATA_STORE: ("[(", ")]"),
             ElementType.EXTERNAL_ENTITY: ("[", "]")}
    lines = ["flowchart LR"]
    by_zone: dict = {}
    for el in model.elements:
        if el.type == ElementType.DATA_FLOW:
            continue
        by_zone.setdefault(el.zone, []).append(el)
    for z, els in by_zone.items():
        lines.append(f"  subgraph {z.value}[\"{zlabel.get(z, z.value)}\"]")
        for el in els:
            o, c = shape[el.type]
            lines.append(f'    {el.id}{o}"{el.name}"{c}')
        lines.append("  end")
    for i, fl in enumerate(model.flows):
        s, d = model.element(fl.source), model.element(fl.dest)
        crosses = bool(s and d and s.zone != d.zone)
        arrow = "-. insecure .->" if (crosses and not fl.encrypted) else "-->"
        label = ",".join(fl.data) or "data"
        lines.append(f"  {fl.source} {arrow}|{label}| {fl.dest}")
    return "\n".join(lines) + "\n"


def to_shields_badge(threats: list[Threat]) -> str:
    """shields.io endpoint JSON summarizing the threat posture (for a README badge)."""
    crit = sum(1 for t in threats if t.risk_level == "Critical")
    high = sum(1 for t in threats if t.risk_level == "High")
    total = len(threats)
    if crit:
        color, msg = "red", f"{crit} critical, {high} high / {total}"
    elif high:
        color, msg = "orange", f"{high} high / {total}"
    elif total:
        color, msg = "yellow", f"{total} (none high)"
    else:
        color, msg = "brightgreen", "0"
    return json.dumps({"schemaVersion": 1, "label": "threats", "message": msg,
                       "color": color}, indent=2)


def _rule_name(title: str) -> str:
    return "".join(w.capitalize() for w in title.replace("/", " ").split())[:60]


def _cwe_uri(cwe: str) -> str:
    if cwe and cwe.upper().startswith("CWE-"):
        return f"https://cwe.mitre.org/data/definitions/{cwe.split('-')[1]}.html"
    return "https://owasp.org/www-community/Threat_Modeling"


def _security_severity(risk: int) -> float:
    # Map 1..25 risk to the 0..10 scale GitHub code scanning uses for sorting.
    return round(min(10.0, risk / 25 * 10), 1)


def _s(s: str) -> str:
    return s.replace('"', "'").replace("\n", " ")


def _var(eid: str) -> str:
    v = "".join(ch if ch.isalnum() else "_" for ch in eid)
    return f"e_{v}"
