# pytm model generated by ThreatForge (threats-as-code).
# Review and extend in pytm: https://github.com/OWASP/pytm
from pytm import TM, Server, Datastore, Actor, Dataflow, Boundary

tm = TM("Sample Web App")

b0 = Boundary("Internet -> Application")
b1 = Boundary("Application -> Third-party")
b2 = Boundary("Application -> Data")

e_app = Server("Sample Web App Service")
e_end_user = Actor("End User")
e_store_11 = Datastore("SQLite Database")
e_third_party = Actor("Third-party API")

df0 = Dataflow(e_end_user, e_app, "user request")
df0.protocol = "https"
df0.isEncrypted = True
df0.data = "credentials, pii"
df1 = Dataflow(e_app, e_store_11, "persist")
df1.protocol = "tcp"
df1.isEncrypted = False
df1.data = "credentials, pii"
df2 = Dataflow(e_app, e_third_party, "outbound call")
df2.protocol = "https"
df2.isEncrypted = True
df2.data = "payment, request"

# --- ThreatForge candidate threats (for review) ---
# [TF-008] Spoofing / End User: Unauthenticated external actor can impersonate a legitimate user (risk 16 High; ASVS-2.1.1, NIST-IA-2, NIST-IA-5)
# [TF-001] Spoofing / Sample Web App Service: Process accepts requests without verifying caller identity (risk 16 High; ASVS-2.1.1, NIST-IA-2)
# [TF-011] Information disclosure / SQLite Database: Sensitive data at rest is not encrypted (risk 15 High; ASVS-8.3.4, NIST-SC-28)
# [TF-014] Information disclosure / SQLite Database: Sensitive data is exposed in transit (risk 15 High; ASVS-9.1.1, ASVS-8.3.1, NIST-SC-8)
# [TF-006] Elevation of privilege / Sample Web App Service: Missing or weak authorization enables privilege escalation (risk 15 High; ASVS-4.1.1, ASVS-4.1.3, NIST-AC-3, NIST-AC-6)
# [PRIV-008] Disclosure of information / SQLite Database: Personal data is disclosed across a boundary (risk 12 High; GDPR-ART5-MIN, NIST-PT-3)
# [PRIV-004] Identifiability / SQLite Database: Individuals are identifiable (no data minimisation/anonymisation) (risk 12 High; GDPR-ART5-MIN, NIST-PT-3)
# [TF-013] Tampering / SQLite Database: Data in transit can be tampered with across a trust boundary (risk 12 High; ASVS-9.1.1, NIST-SC-8)
# [PRIV-007] Disclosure of information / Sample Web App Service: Personal data is disclosed across a boundary (risk 12 High; GDPR-ART5-MIN, NIST-PT-3)
# [TF-002] Tampering / Sample Web App Service: Untrusted input reaches the process without validation (risk 12 High; ASVS-5.1.3, ASVS-5.3.4)
# [PRIV-009] Disclosure of information / Third-party API: Personal data is disclosed across a boundary (risk 12 High; GDPR-ART5-MIN, NIST-PT-3)
# [TF-007] Elevation of privilege / Sample Web App Service: Internet-facing path can reach privileged/admin functionality (risk 10 Medium; ASVS-4.1.1, NIST-AC-6)
# [PRIV-002] Unawareness / End User: Data subject may be unaware of processing (no consent signal) (risk 9 Medium; GDPR-ART13)
# [PRIV-003] Linkability / SQLite Database: Records are linkable across contexts (no pseudonymisation) (risk 9 Medium; GDPR-ART25, NIST-PT-3)
# [TF-005] Denial of service / Sample Web App Service: No rate limiting on an internet-facing process (risk 9 Medium; ASVS-11.1.4, NIST-SC-5)
# [TF-003] Repudiation / Sample Web App Service: Security-relevant actions are not auditable (risk 9 Medium; ASVS-7.1.3, NIST-AU-2, NIST-AU-9)
# [PRIV-006] Unawareness / Third-party API: Data subject may be unaware of processing (no consent signal) (risk 9 Medium; GDPR-ART13)
# [PRIV-005] Non-compliance / SQLite Database: No retention/governance controls on personal data (non-compliance) (risk 8 Medium; GDPR-ART5-STORAGE, NIST-SI-12)
# [TF-009] Tampering / SQLite Database: Stored data can be modified without detection (risk 8 Medium; ASVS-1.9.2, NIST-SI-7)
# [TF-012] Denial of service / SQLite Database: Unbounded growth or connection exhaustion in the store (risk 6 Medium; NIST-SC-5)
# [TF-010] Repudiation / SQLite Database: Writes to the store are not attributable (risk 6 Medium; ASVS-7.1.3, NIST-AU-2)
# [PRIV-001] Disclosure of information / Sample Web App Service: Process may over-collect or over-expose personal data (risk 6 Medium; GDPR-ART5-MIN, NIST-PT-3)
# [TF-004] Information disclosure / Sample Web App Service: Verbose errors or responses leak internal detail (risk 6 Medium; ASVS-7.4.1, ASVS-14.3.2)

if __name__ == "__main__":
    tm.process()
