"""Threat -> verification: generate a security test and a detection rule per threat.

Closes the loop. For each threat ThreatForge emits:

* a **pytest** stub that encodes the mitigation as an assertion a team can wire to
  their system ("assert the login endpoint rate-limits after N attempts"), and
* a **Sigma** detection rule skeleton for the corresponding attack, so the threat
  is not just documented but *testable* and *detectable*.

These are deliberately scaffolds, not magic: each is grounded in the threat's KB
pattern (so the generated check matches the specific weakness) and is clearly
marked for a human to complete with system-specific details. That honesty is the
point - a generated test that silently passes is worse than none.
"""

from __future__ import annotations

import re

from ..reason.threat import Threat

# Per-pattern hints for what the generated test should assert and what the
# detection rule should look for. Keyed by KB pattern id; falls back to STRIDE.
_TEST_HINTS = {
    "S-EXT-AUTHN": "assert repeated bad-credential logins get locked out / MFA required",
    "S-PROC-WEAKAUTH": "assert an unauthenticated request is rejected (401/403)",
    "T-PROC-INPUT": "assert a malformed / injection payload is rejected or sanitized",
    "T-FLOW-NOTLS": "assert the endpoint refuses plaintext HTTP and requires TLS",
    "I-FLOW-PLAINTEXT": "assert sensitive fields are never sent over plaintext",
    "I-STORE-ATREST": "assert stored sensitive columns are encrypted (not plaintext)",
    "I-PROC-ERRORS": "assert error responses contain no stack trace / internal detail",
    "D-PROC-RATELIMIT": "assert the endpoint rate-limits (429) after a burst",
    "E-PROC-AUTHZ": "assert a low-privilege user cannot access another user's object",
    "E-PROC-ADMIN": "assert admin endpoints are unreachable from the public path",
    "R-PROC-LOG": "assert a security event is written to the audit log",
    "R-STORE-LOG": "assert a data change records an attributable audit entry",
    "T-STORE-INTEGRITY": "assert unauthorized store modification is detected/rejected",
    "D-STORE-EXHAUST": "assert oversized / unbounded writes are rejected",
}

_SIGMA_HINTS = {
    "S-EXT-AUTHN": ("authentication", "Multiple failed logins followed by a success (credential stuffing)"),
    "S-PROC-WEAKAUTH": ("webserver", "Requests to protected routes without an auth token"),
    "T-PROC-INPUT": ("webserver", "Injection-like payloads in request parameters"),
    "D-PROC-RATELIMIT": ("webserver", "High request rate from a single source (flood)"),
    "I-PROC-ERRORS": ("application", "Responses containing stack traces or internal paths"),
    "E-PROC-AUTHZ": ("webserver", "Access to object ids the principal does not own (IDOR)"),
    "R-PROC-LOG": ("application", "Security-relevant action with no corresponding audit entry"),
}


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def generate_pytest(threats: list[Threat]) -> str:
    """Emit a single pytest module with one stubbed test per threat."""
    lines = [
        '"""Security verification tests generated by ThreatForge.',
        "",
        "Each test encodes a threat's mitigation as an assertion. They are STUBS:",
        "fill in the `# TODO` with a real call to your system, then remove the skip.",
        "A generated test that silently passes is worse than none - so every test",
        "starts skipped until a human wires it to the system under test.",
        "",
        "Author: Krishita Sanjay Choksi.",
        '"""',
        "",
        "import pytest",
        "",
    ]
    for t in threats:
        hint = _TEST_HINTS.get(t.source_pattern) or f"assert the mitigation for {t.stride_name} holds"
        fn = f"test_{_slug(t.component)}_{t.stride.lower()}_{_slug(t.source_pattern or t.id)}"[:80]
        lines.append(f'@pytest.mark.skip(reason="ThreatForge stub - wire to the system under test")')
        lines.append(f"def {fn}():")
        lines.append(f'    """[{t.id}] {t.title} ({t.component}).')
        lines.append(f"")
        lines.append(f"    Mitigation under test: {t.mitigation}")
        lines.append(f"    Controls: {', '.join(t.controls) or '-'} | CWE: {t.cwe or '-'}")
        lines.append(f'    """')
        lines.append(f"    # TODO: {hint}.")
        lines.append(f"    #       Arrange the system, exercise the path, then assert.")
        lines.append(f"    raise NotImplementedError")
        lines.append("")
    return "\n".join(lines)


def generate_sigma(threats: list[Threat]) -> list[dict]:
    """Emit Sigma detection-rule skeletons (as dicts) for detectable threats."""
    rules = []
    for t in threats:
        hint = _SIGMA_HINTS.get(t.source_pattern)
        if not hint:
            continue
        logsource, desc = hint
        rules.append({
            "title": f"ThreatForge: {t.title} ({t.component})",
            "id": f"threatforge-{_slug(t.id)}",
            "status": "experimental",
            "description": f"{desc}. Generated from threat {t.id}; tune to your environment.",
            "references": [u for u in [_cwe_ref(t.cwe)] if u],
            "author": "Krishita Sanjay Choksi (generated by ThreatForge)",
            "tags": _attack_tags(t),
            "logsource": {"category": logsource},
            "detection": {
                "selection": {"_comment": f"TODO: define fields that match: {desc}"},
                "condition": "selection",
            },
            "falsepositives": ["Legitimate activity - tune before enabling"],
            "level": {"Critical": "high", "High": "high", "Medium": "medium",
                      "Low": "low"}.get(t.risk_level, "medium"),
        })
    return rules


def generate_sigma_yaml(threats: list[Threat]) -> str:
    import yaml
    rules = generate_sigma(threats)
    if not rules:
        return "# No detection-rule templates available for the current threats.\n"
    return "\n---\n".join(yaml.safe_dump(r, sort_keys=False) for r in rules)


def _cwe_ref(cwe: str) -> str:
    if cwe and cwe.upper().startswith("CWE-"):
        return f"https://cwe.mitre.org/data/definitions/{cwe.split('-')[1]}.html"
    return ""


def _attack_tags(t: Threat) -> list[str]:
    tags = ["threat-model"]
    if t.attack_technique:
        m = re.search(r"\bT\d{4}\b", t.attack_technique)
        if m:
            tags.append(f"attack.{m.group(0).lower()}")
    return tags
